import { config } from "@fortawesome/fontawesome-svg-core";
import { Inter } from "next/font/google";
import Copyright from "@/app/ui/copyright";
import Footer from "@/app/ui/footer";
import GlobalSearch from "@/app/ui/global-search";
import Header from "@/app/ui/header";
const inter = Inter({ subsets: ["latin"] });
config.autoAddCss = false;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
    <div className="">
      <div className="flex  flex-col">
        <Header />
        <GlobalSearch />
      </div>
      <div className="">{children}</div>
      <div className="flex flex-col">
        <Footer />
        <Copyright />
      </div>
    </div>
  );
}
