import Header from "../ui/header";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
        <div className="">
          <div className="flex justify-center items-center flex-col">
            <Header />
          </div>
          <div className="">{children}</div>
        </div>
  );
}
