import { Inter } from "next/font/google";
import Header from "../ui/header";
const inter = Inter({ subsets: ["latin"] });
import { config } from "@fortawesome/fontawesome-svg-core";
import GlobalSearch from "../ui/global-search";
import Copyright from "../ui/copyright";
import Footer from "../ui/footer";
config.autoAddCss = false;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
    <div className="">
      <div className="flex flex-col">
        <Header />
        <GlobalSearch />
      </div>
      <div className="">{children}</div>
      <div>
        <Footer />
        <Copyright />
      </div>
    </div>
  );
}
