import { Inter } from "next/font/google";
import Header from "../ui/header";
import { config } from "@fortawesome/fontawesome-svg-core";
import Footer from "../ui/footer";
import Copyright from "../ui/copyright";
import GlobalSearch from "../ui/global-search";
const inter = Inter({ subsets: ["latin"] });
config.autoAddCss = false;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
    <div className="">
      {/* <Image
        src="/background1.png"
        layout="fill"
        objectFit="cover"
        quality={100}
        alt="background image"
      /> */}
      <div className="flex flex-col">
        <Header />
        <GlobalSearch />
      </div>
      <div className="">{children}</div>
      <div>
        <Footer />
        <Copyright />
      </div>
    </div>
  );
}
