import Header from "@/app/ui/header";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
const inter = Inter({ subsets: ["latin"] });
config.autoAddCss = false;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
        <div className="">
          <div className="flex justify-center items-center flex-col"></div>
          <div className="">{children}</div>
        </div>
  );
}
